# Generated by Django 4.2.5 on 2023-10-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAlumno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debe_cuotas', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
    ]
