# Generated by Django 4.2.5 on 2023-10-17 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppAlumno', '0003_alter_cuota_debe_cuotas_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiasaprobadas',
            name='Nota_del_final',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materiasaprobadas',
            name='Nota_primer_parcial',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materiasaprobadas',
            name='Nota_segundo_parcial',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
