# Generated by Django 4.2.5 on 2023-10-17 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAlumno', '0004_materiasaprobadas_nota_del_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='importe_a_pagar',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
